"""Add customer_id to service_tickets

Revision ID: 94279a6dd116
Revises: 
Create Date: 2025-04-12 18:49:49.224639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94279a6dd116'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tickets', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'service_tickets', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_tickets', type_='foreignkey')
    op.drop_column('service_tickets', 'customer_id')
    # ### end Alembic commands ###
